services:
  prometheus:
    image: prom/prometheus
    container_name: "prometheus-1"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    container_name: "grafana-1"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki
    container_name: loki-1
    command:
      - "--config.file=/etc/loki/loki-config.yaml"
      - "-validation.allow-structured-metadata=false"
    ports:
      - "3100:3100"
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-1
    ports:
      - "9093:9093"
    restart: always
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  prom_data: