services:
  promtail:
    image: grafana/promtail
    volumes:
      - ./config.yml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: 
      - "-config.file=/etc/promtail/docker-config.yaml"
    networks:
      - app
    restart: always

networks:
  app:
    name: app